spring:
  application:
    name: Config-Default

eureka:
  instance:
    prefer-ip-address: true  # Use IP instead of hostname when registering

  client:
    fetch-registry: true      # Fetch registry information from Eureka
    register-with-eureka: true  # Register this service with Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL
